### PR TITLE
generate.ts: upgrade devDependencies

### LINKED ISSUE #3: yarn error on start
Following the instructions I got this yarn error on `yarn start`

```
yarn run v1.10.1
$ webpack-dev-server --open --mode development --devtool inline-source-map
/Users/ac/Projects/18-09-instore/code/prototyping/ui/my-app/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
```

### PR DESCRIPTION
**Pull request by acarabott**
solves issue of build failing, fixes #3

### CODE REVIEW

**Comment by postspectacular** [comment]
Thanks, @acarabott !!! 🥇 I was actually going to replace webpack w/ parcel (like w/ all the other umbrella example projects), but didn't get to it yet...

at least this works for now!

**Comment by acarabott** [comment]
👍 

Will check out Parcel, in my other projects I moved from Webpack to just compiling to ES6 modules as something in the bundling was increasing audio artefacts on iOS Safari.

**Comment by postspectacular** [comment]
hmm.. maybe webpack/babel started polyfilling some constructs it shouldn't have? I had that problem initially with Parcel too, but then learned that I can set a "browerslist" config in `package.json` to stop it from going all legacy on me :) E.g.

https://github.com/thi-ng/umbrella/blob/master/examples/xml-converter/package.json#L25

**Comment by JJ-Atkinson** [comment]
I still have the same errors on my machine. If yall get around to it would be great to have working!

**Comment by postspectacular** [comment]
@JJ-Atkinson hey - so sorry for not updating this, I will put a note on the readme that this template is somewhat out of date. There have been hundreds of updates to the umbrella repo meanwhile, incl. some breaking changes to hdom itself, which need to be reflected here in this scaffolding. Time's the enemy! :)

With the release of [GH templates](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/) I will probably phase out this project soon and replace with a ready to go repo...

**Pull request merged**
